language: ruby
rvm:
  - 2.3.3
cache: bundler
branches:
  only:
    - master
addons:
  apt:
    packages:
      - diffstat
install:
  - travis_retry sudo apt-get -y update
  - travis_retry sudo apt-get remove -y subversion git
  - travis_retry sudo add-apt-repository "deb http://ppa.launchpad.net/svn/ppa/ubuntu precise main"
  - travis_retry sudo add-apt-repository -y ppa:git-core/ppa
  - travis_retry sudo apt-get -y update
  - travis_retry sudo apt-get install -y git
  - travis_retry sudo apt-get install -y subversion
  - travis_retry bundle install
  - svn --version
  - git --version
  - diffstat --version
script:
  - rake
after_success:
  - "bash <(curl -s https://codecov.io/bash)"

